name: 'Flake8 with annotations'
author: 'Patric "TrueBrain" Stout'
description: 'Flake8 with annotations for Pull Request'
inputs:
  path:
    description: 'Path to run flake8 in'
    required: false
    default: ''
  ignore:
    description: 'Skip errors and warnings (e.g. E4,W)'
    required: false
    default: ''
  max_line_length:
    description: 'Set maximum allowed line length'
    required: false
    default: ''
  only_warn:
    description: 'If set, only warn, never error'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
